export const HOME_GET_NOW_PLAYING_MOVIES_REQUEST = 'elotus/home/HOME_GET_NOW_PLAYING_MOVIES_REQUEST';
export const HOME_GET_NOW_PLAYING_MOVIES_SUCCESS = 'elotus/home/HOME_GET_NOW_PLAYING_MOVIES_SUCCESS';
export const HOME_GET_NOW_PLAYING_MOVIES_FAILURE = 'elotus/home/HOME_GET_NOW_PLAYING_MOVIES_FAILURE';

export const HOME_GET_TOP_RATED_MOVIES_REQUEST = 'elotus/home/HOME_GET_TOP_RATED_MOVIES_REQUEST';
export const HOME_GET_TOP_RATED_MOVIES_SUCCESS = 'elotus/home/HOME_GET_TOP_RATED_MOVIES_SUCCESS';
export const HOME_GET_TOP_RATED_MOVIES_FAILURE = 'elotus/home/HOME_GET_TOP_RATED_MOVIES_FAILURE';

export const HOME_SEARCH_MOVIES_REQUEST = 'elotus/home/HOME_SEARCH_MOVIES_REQUEST';
export const HOME_SEARCH_MOVIES_SUCCESS = 'elotus/home/HOME_SEARCH_MOVIES_SUCCESS';
export const HOME_SEARCH_MOVIES_FAILURE = 'elotus/home/HOME_SEARCH_MOVIES_FAILURE';
